language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_HOST
    - secure: "Gau/qG10nh02DM1VvVH8EZlXHhbYQ1G2VRLLXVogXZ+HOv32O2/2E8SKSldVJyIorO4bAFjsIRE3NwxwRuMwqKAOmHoR0X3XoSZcil414I+tO3UrDGNDBb+NR1xru6u+1ghyiwoBtLjw9s32/RV2BplNrLqPots8IqzWishsiPH0MJYNrdjF3Ic0SQAsxpNWUPuM54RHFUp1eyBL6x0JudHRNuofEzuR646dQvSFRCeWtwv99zRrAv4DVcWktaJySm9FbSlBhz/DXWaiszFdQQlsriDUDfg4zhYTE1aAy/Uiyr3lWWpMSqRetg1hM/c1c7ZKtKB5rdeXSKjpej6auX3thsTSM/GJmykrbwabjnWf39zU4RdFTyhVx8BLXSePnDSg14Xr0X8mYYC9zOnRYByDTYvHUZ+qcMCqYJg8Vw2+N7yURCVN2lXuatddKEqK+M51Sg7aoRKIvLHQcy3CmeEB6e7ozQvWFQo2nHBSodLz0guGlBM2Vz82dc1vyxLkPKZFws5zfX5xeLg3OqBNVEWWyBhTlaPkJS+G/IvnEYXn5laV3jsZdRFYaD/YLb4cXDgNZHhfFhWgl1Q7gEqaEhNVn0lwEyxs5zIMs7yF1/YCEljxDnhxSi4Tdl316LRqpL2HKiIFZELUwwA7OnMra/ohQT1CeirhStor8LDWwAs="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
